# fly.toml app configuration file generated for daxthebot-soft-shape-4207 on 2026-07-27T02:59:37+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'daxthebot-soft-shape-4207'
primary_region = 'ams'

[build]

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
