name: Dax status check
on:
  schedule:
    - cron: '7,37 * * * *'
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: node monitoring/status-check.js
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_ORG_SLUG: ${{secrets.FLY_ORG_SLUG}}
          FLY_ORG_TOKEN: ${{secrets.FLY_ORG_TOKEN}}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}